sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.14.0
  matrix:
    - COMPOSE_FILES=""
    - COMPOSE_FILES="-f docker-compose.yml -f docker-compose.test.yml"
    - COMPOSE_FILES="-f docker-compose.yml -f docker-compose.prod.yml"

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose ${COMPOSE_FILES} up --build -d

script:
  - docker-compose ${COMPOSE_FILES} run app python manage.py test

after_script:
  - docker-compose ${COMPOSE_FILES} down
