version: '2'
services:
  app:
    environment:
      - APP_SETTINGS=app.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app
    command: gunicorn -b 0.0.0.0:5000 manage:app