version: '2'
services:
  app:
    volumes:
      - .:/usr/src/app
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app