version: '2'
services:
  nginx:
    build: nginx/.
    restart: always
    ports:
      - "80:80"
    links:
      - app
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app
    links:
      - postgres
  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
